version: '3.4'
services:
  test-database:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - 5432:5432

volumes:
  db-data:
